luku1 = input ("Anna kokonaisluku: ")
luku2 = input ("Anna toinen kokonaisluku: ")
summa = int(luku1) + int(luku2)
erotus = int(luku1) - int(luku2)
tulo = int(luku1) * int(luku2)
osa = int(luku1) / int(luku2)
print("Summa:", summa)
print("Erotus:", erotus)
print("Tulo:", tulo)
print("Osamäärä:", osa)